### ISSUE TITLE
Leer fichero XML y explicar su estructura.

### ISSUE THREAD

**Issue by Animorales** [Adalab/project-da-promo-C-module-1-team-5#16]
Leer el fichero xml

**Comment by MartaOrdas** [comment]
Los datos contenidos en el archivo xml son estructurados y tienen un formato bien definido.
Conforman una lista de diccionarios de 5 tuplas cada uno, en los que las keys son strings tipo varchar y los values son numéricos tipo integer.

Las dos primeras categorías son claves (presentan un valor único para cada registro) y devuelven datos monovaluados de tipo integer autoincremental.

La categoría “género” aparece inicialmente codificada y habrá que realizar la descodificación necesaria, lo que proporcionará valores tipo texto para dicha variable.

**Comment by Animorales** [comment]
El archivo contiene  una lista  que contiene 25972 diccionarios.
