### ISSUE TITLE
Cambiar la variable genero a texto para el fichero XML.

### ISSUE THREAD

**Issue by Animorales** [Adalab/project-da-promo-C-module-1-team-5#19]

**Comment by VannaLZ** [comment]
for dictionary in list_hml_10_dict:
    if dictionary.get('gender') == '0':
        dictionary['gender'] = 'Man'
    elif dictionary.get('gender') == '1':
        dictionary['gender'] = 'Woman'
    elif dictionary.get('gender') == '2':
        dictionary['gender'] = 'Nonbinary'
    elif dictionary.get('gender') == '3':
        dictionary['gender'] = 'Prefer not to say'
    elif dictionary.get('gender') == '4':
        dictionary['gender'] = 'Prefer to self-describe'
    else:    
       print(f"There is an error, the unlisted values is : {dictionary.get('gender')}")

**Comment by VannaLZ** [comment]
1. La variable gender esta codificada y deberemos cambiarla así :

gender        	gender_text
0		    	Man
1			Woman
2			Nonbinary
3			Prefer not to say
4			Prefer to self-describe

1. Sabemos que el fichero XML es una list que contiene dictionary
2. Se crea una variable test (en este caso decidí para list_hml_3_dict)
3. Creamos un FOR utilizando la variable dictionary que va a correr para la variable test.
4. Creamos un hilo de IF, ELIF,ELSE para que por cada numero corresponda un gender como en el esquema de arriba.
5. Para acceder al value de la key gender del dictionary usamos .get(‘gender’)
6. En el ELSE ponemos una frase para que nos devuelva el value que no está en el esquema y que lo podamos revisar
