### ISSUE TITLE
# Working agreements #

### ISSUE THREAD

**Issue by MartaOrdas** [Adalab/project-da-promo-C-module-1-team-5#2]

**Comment by MartaOrdas** [comment]
- [ ]     Daily: 13:30-13:40
- [ ]     Canal de comunicación: Mensajes = Slack, Reuniones =  Zoom, Reuniones fuera de horario = Google meet
- [ ]     SCRUM master sprint 1: Anahí, SCRUM master sprint 2: ¿?
- [ ]     Definir los horarios de trabajo: 13:40- 14:30/ coordinación fuera del horario presencial de Adalab: se decidirá durante la daily.
- [ ]     Definir como se compartiran los aprendizajes del proyecto entre las miembros del equipo.
- [ ]     Definir plan de contingencia por ausencia de alguna compañera.
- [ ]     Establecer como se trabajara las tareas: Individualmente, en parejas, por equipos.
- [ ]     Utilizar la normativa PEP - 8 y definir la version de Python a utilizar.
- [ ]     Los mensajes de los commits deben ser claro
- [ ]     Comentar el código de forma adecuada
- [ ]     Definir como se toman las decisiones de equipo
- [ ]     Establecer alguna actividad que fomente el team building
- [ ]     Celebrar los exitos ( cerveza- telecerveza -otros)
- [ ]     Definir como solucionamos los bloqueos del equipo.

**Comment by Animorales** [comment]
- [ ]     **Daily:**  13:30-13:40
- [ ]     **Canal de comunicación:** Mensajes = Slack, Reuniones =  Zoom, Reuniones fuera de horario = Google Meet/ Zoom
- [ ]     **Scrum master Sprint 1:** Anahí, **Scrum master sprint 2:** ¿? / **Scrum master suplente Sprint 1:**Vanna
- [ ]     **Horarios de trabajo:** 13:40- 14:30 ( hasta las 15:00 h si no hay tutorías) / coordinación **fuera del horario presencial de Adalab:**  se decidirá durante la daily.
- [ ]     **Aprendizajes del proyecto:**  -Buenas practicas haciendo comentarios en el desarrollo de los ejercicios (#) - Carga de archivos en repositorio GitHub 'project-da-promo-C-module-1-team-5  - Jupyter con anexo de información.
- [ ]     **Ausencias:** -Scrum master Suplente. - Suplantar tareas de manera equitativa (en caso de dificultades avisar al resto de las compañeras. -
- [ ]     Establecer cómo se trabajara las tareas: Individualmente, en parejas, por equipos. **Gestión de tareas:**  Vemos con el correr de las tareas.
- [ ]     Utilizar la normativa PEP - 8 y definir la version de Python a utilizar.
- [ ]     Los mensajes de los commits deben ser claro.
- [ ]     Comentar el código de forma adecuada.
- [ ]     Definir como se toman las decisiones de equipo **Metodología toma de Decisiones:** Mayoría (en caso de empate Random de Python)
- [ ]     **Actividades Team Building:** Viernes relax.
- [ ]     Celebrar los éxitos (queda por definir) 
- [ ]     Definir cómo solucionamos los bloqueos del equipo. **Pasos a seguir en caso de bloqueo grupal** 1) Describir dónde esta el bloqueo a mis compañeras 2) Pedir tutoría.
- [ ]   Definir Presentación de proyecto.
